# Generated by Django 2.1.5 on 2019-01-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_image_path', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
            ],
        ),
    ]
