# Generated by Django 2.1.5 on 2019-01-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_blurb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
