# Generated by Django 2.1.7 on 2019-05-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190127_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_path',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
