language: python
python: 3.6
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: K1fQBaI1bzqzB7kgQIkpMuJ5xO0AE6ZIRICfQvutW/Le0rzitqPun4uudONBOsn4A+2ZTVcc5p6IZsuDOyh1hdsjl+hiuJj9qik3rtVhmhiUAFrSXrhTitCM427+MOSJDc7yA4NlbAu/Z5AvpAAychoY3xsSmiZkd+RPfxZ9AdyOgKf71F0oDC7HFCodx/7K0UQvW9hUX4i2g9TcMC5p9hu8XKaUWToC45VmGI3RU0FoIOXv6XMeqV8VmXomDyeccubLHHggzq10Z+zslTME2JM+gQ/pqaVz1OJll7Klzuplnj5QDfymJOzp2u9SG25XOW2QMz14gRjY9N6wCmVzPdTa/mADd1oRqT/xvfiX4f1dDkEx5ZbJJXrITwrsA2G22bbc6adK8B3RW9Du1PHdnzRAl9bHxpC9GvI1tbn1GhdXNNog1QOrX7Uly8kr5zOsDdVKzQl1SB9XVgXvMEWPSBHVmPq1VDFw/NJkDoY5w9n2oMqTRmJQaKwvq9nwJ345N3e8iee8ZpZWBYoo+943PTq6gNLmQ01tpHNIK8kQVC5hFzpBdQLTSow/3ahfWCwPauGljnDipOT5+7pGhSCV0T8SN9+OOjCiaDHw2kiz5zIQnZuEICJIutwlPs2QEZGPQrb1KmNx7p5S6p6MYuhlZm1ufhCaQzEQ5IhXTfm+vEU=
  on: master
