language: python
python: 3.9
before_install:
- pip install poetry
- poetry --version
install:
- poetry install --no-root -v
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: FsGQjNWIYUfz3+pwoKfBSIXKOFbKz74aZuCL1sOXnX3zZLSEwQ4Hlle32hjugrzYuqWNUX/gXg1bi8zJVcjS3xx9Si+jbZiY7LMLxCFFouLrfXxyJ3u2w2vepOpYRobbPCr0z6ubji4wf8UDmjDWGO6KD18CCpgCFlhd84xxApdCY2xbC9oXt/vMOPmyfIK1CT+thFSmQDVFw6mN88indJ2DkD8L17NE54duGQtwrtou5WAb4YrN1OJuO3aI38UipWLpkNdhBrJklhJjq0DhEDKkgX8KtLruz0+uUf4tLameaKJQijBsrpQSKDv5nu6d8dP6ZoRqNLcaKSGmnmu5EtYaQy3U7+a7KupQEkHejvZeCC6hW4w7CLfs9y07Jj6pSRvxSiljdzkkKEFNMDMTUgNEquKY7j1FDxNapbvST5eoSD4jHNk/FiG5yp4sWPVgCeqahNGYKx/MrG7qz50H8JCrnblbTFC6LfupcQ1S1OYtGP6JKvupJQPIzeiM1kjATC0MXNAmnxl8SR6chhdciL9z7wtn6NpZ0NEZzfI8rGz6ysVKKif9VcF1lL6Ht5S3SH1yWSq/+7wvr/BJJhhZZ8vBWcQ7BycjHg11wv/Z4j8XSyGY2atGYv7bU8+bETGTRwxxiFwnAm0x2l6/u0Qig7KlxiuzQl2yDqE2HZQn+ng=
  on: master
