language: python
python: 3.6
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: uFN1nyMNckKhKqrgN04iBUZF1d4YY+Ichikc1btLRMqW3mle9P6ERrZax8ShhQyZgfdyH6j3ZuQUdohGfn+Nw+WqAehZ395lwCxkCHNU79rpq2IzPiRSmiZx0iU0ercGmlOGINTow2xN9ftKGnpTAfyj6DXgiCl0XxmjzW8cMmxNBotFYtZiA5xiIg0Q8A/zDkRxe4mNYbyM/H4v5gxWeNGApv2MbLWBRppGOac94d2ml/fdXQTEc1tb6Fl0AxPFe6DEBgB12FFbe3mGGVzBGnhvwytmwW7Md3Dog1EUcIX/Gd1fM53aEmocRAenUU7stDJk0dGSqLUO0Lh0VgQkh7S+gPFhxBp+mGDMeOkVTK/ZmzePxfxYYcf3CFzhJj1Qo0u+oDrRwOG04FPG/5uDrNLPUkC2xXVhlRO0vxnDmgyD4hgDkHqLSaR+bfwHxXsA0dUZy2yv+329DKuEZjMd7vk1WNSXIODLiAt3S6lmEPvEpbopQpT29Hvm1pUx0bNh6a7oXZeagce+VgySjom5hW3AGxS68tmRNZun6gP7XcHTQ3mBWWzty9EOGA9gVwFNIsaH7oSmHoDdpxO8D5UjQvJzSoATT7N1McRuwNEzuH1jwW72GBnEr8vbiUL2oIDYJOzklNHNYKHq3L4XLzorhHIbKVYDrcJYHChBwtiXDNA=
  on: master
