language: python
python: 3.6
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: bVIs0ATmfd0gvW2OknWHTa0TtYFSdZfqO8M3bzdC6lNS9wLSiD6bqfW4mvIlGcuwOyPO9W0Y4IFvSM1Y3XiWaLu/3pkhc/jjIh41Pn/uflMiL6cgyyGgGqm7Rbs6hH0ReWZtffOFVpuDk38c8L+nvatv9HUICJtgnrWoS4Z8tHwNPJpyjY96LN92+cG3giYEpRGXxiv/MGeXXrNfuhKI22nmDviWcWVqfoDKN8XvDXfdGCy9G/jimMVCPsA6U+RbYIbUyyLcgM4LIb5hYL/80p2Nu1yS3s+JtYdz73nIsFGqSEwtgfoK6zxeodbubuhP+6Nl19k004jnO90FfeWQ4DtovpI6ezAK8XUIu9opfmuHiQoirNUkVmFtKGnrklb7ZiY8KzjwMHFLP9qn84ZZGMsVcibgI5vHizvEEUGt85bJ0NeLatySXAk7jEmDRS2GiHgwcGw1VaeVQwfVHNj6cG4RFPHRCaIs8KlOF2EsuAXkgLDRplgYTqx4rmeba/zT3x3aYV67iDej1Z52Jh6lzchpjWrRoF99ey9Jy4hO8ZvQPsViMREMqIrJj7odSRnsEpQ9P1oNTVrUruH8/Zk7L+jC4irdqCPC0mvxVO4WZQga8/J/mnAcPaCdnRAlb5gbmirSOcYfKceoSFV1HaEqxYv4eHdz5aM8XMiJqM1SvKA=
  on: master
