language: python
python: 3.6
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: rMxj8LRXWXEwE8xESjQoNRE+3DTCF/wrj/7KMbq4MCdf7XEvETCa3QDp1zJZQU3+FtBGCQj6rIO7QaJHUnnA1veAcdzC4GklL82gtm+2/9gNvi9I7ELoasfJRVuH6yuygvItW5fBCdslzV04khfVoBrYZKU0tBtiuZ368L0+StpfosUANcbg8gF5nVmSF5ooJhjQSkiOiGL51QDAzA31kB1uheODPwa1o4BCTDgN6uZhSwUp9FDZF//XbpbwOC75uuIXedYTvVeLhNIZFMiLgb0DUX6AvJRo/vBeSqiweh0o7TCWroZzGA46kRMkz3BDb8fY4q9+OX6Gv+Xqtg4XVeTtYKR2pR/Y39c62h1ssBSoVJWrJWsNgv5Q/Krqy4J3NLugg84VWd1gjabo30iXntVo0HT6YxqeKeFsXC5WXn4pjnOXRTP9xpI20GxVuON8PKzr93tBXNuzuBnXdX1FRXg9TASBqxSW51lNnZVJDpOdoFIXMjTNbgLW2HNv08zyeIwq5IgNUWHMrccyqJ/d5rYeDGJbJ1Pf4yibdKDEA2zkmnvDfebKBeyEnU4YXWv9t3Gjr2qIn7B8OZOgV6y+CBrJb5yjpwCrDZMwchYLuwD96iADhD8ITf4pRVYJxQzNm3Ohj/fddspTTIrelWGC4h7EOHEJd84elpBGCyMaTLs=
  on: master
