language: python
script:
  - python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: FWYow2Ws6D1kP8Ogkp+RgXh4AzXejmR7xTYEiX9vm1LSMIiY5VayJXkMvpwEMJH9eaUWwH88qzgtk2EOHaMDVyWByCRyBq2hC626nLG5uxzh4f9rr+T65pIfdWzUJqgr24kXxlEuKVYV5oVA51VRBqR9kZcCnKTO/o1Ra400Ve/pfKCaOPbpnxyBC/J7LMMKdCYdawohESfKPSZPUjEqdgMar4KnrY87/dz7V+mhz5156smzkj7uoucPxww6HKA8Y1Q0mCMRZe4lJasaZm5l+NyrlBr7OwW/1JKdRUJ2oURT2GuXtQhbwtZzmW4I8562Ni/OkY8XQF7RjmIk755Xisd8p0RsVYfMaFUR3PCoJy+ZPslMFzRBJTHmvEM8Mw+fFNDFYuJWz7+qk13vIQJ47sEEj01nmL1SsXiXjRCeyMQo1RZgNLB74BeSTDizwQdMBVJ0ywDhZ/yrJNdH7z69dORiWPFTQwTmkh34QriM9FlrhlCCM9X/17jDloDqeVx40d5sNLpsKIc2YO9Qdv5nlAyVNuqlO5QS5wtlbh4UJUUJRdUoTYzTkRVKiDqVK0jH1bviGI0gdxczGkPOts1JMWYHERTXnp/NkFD6aAUFJMPcfAiHMrfRvnG3B36brg7wihltmfFfQ2CWCN+OuEZwoiuo4fhspQILo6kImSSgilk=
  on: master
