# Generated by Django 2.2.9 on 2020-02-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boards', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_url_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('minimum_boards_required', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=200)),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner_program.Technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('kit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner_program.Kit')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner_program.ReservationRequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaner_program.Technology'),
        ),
    ]
