# Generated by Django 2.0.6 on 2018-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('ES', 'Elementary School'), ('MS', 'Middle School'), ('HS', 'High School'), ('U', 'Post-secondary')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proficiency_description',
            field=models.CharField(blank=True, choices=[('newbie', 'Completely new to STEM (primarily the Technology part).'), ('nerd', 'Familiar with STEM and currently looking to bring it into the classroom.'), ('oldie', "Took classes in post-secondary education, but haven't touched it since."), ('veteran', 'Very familiar with STEM and its use in the classroom.')], max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
