# Generated by Django 2.0.7 on 2018-08-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_profile',
            field=models.BooleanField(default=False),
        ),
    ]
