# Generated by Django 2.0.2 on 2018-04-19 04:13

import curriculum.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('grade_level', models.CharField(choices=[('ES', 'Elementary School'), ('MS', 'Middle School'), ('HS', 'High School')], max_length=2)),
                ('prep_time', models.DurationField()),
                ('class_time', models.DurationField()),
                ('summary', models.CharField(max_length=2000)),
                ('materials', models.CharField(max_length=2000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.SmallIntegerField(choices=[(0, 'Student handout'), (1, 'Teacher reference'), (2, 'Slides'), (3, 'Code'), (4, 'Schematic')])),
                ('file', models.FileField(upload_to=curriculum.models.user_upload_directory)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='resources',
            field=models.ManyToManyField(blank=True, to='curriculum.LessonResource'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='curriculum.Tag'),
        ),
    ]
