# Generated by Django 2.1a1 on 2018-05-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
