# Generated by Django 2.0.5 on 2018-05-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20180527_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonresource',
            old_name='type',
            new_name='semantic_type',
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='mime_type',
            field=models.CharField(blank=True, max_length=129),
        ),
    ]
