# Generated by Django 2.0.5 on 2018-05-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20180531_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(choices=[('ES', 'Elementary School'), ('MS', 'Middle School'), ('HS', 'High School'), ('U', 'Post-secondary')], max_length=2),
        ),
    ]
