# Generated by Django 2.0.5 on 2018-05-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20180531_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='web_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
