# Generated by Django 2.0.5 on 2018-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_lessonplan_web_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfeedback',
            name='notify_author_of_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='notify_of_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
