# Generated by Django 2.0.6 on 2018-07-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_websitefeedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonplan',
            old_name='class_time',
            new_name='single_class_time',
        ),
        migrations.RenameField(
            model_name='lessonplan',
            old_name='prep_time',
            new_name='total_prep_time',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='num_classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='semantic_type',
            field=models.SmallIntegerField(choices=[(0, 'Other'), (1, 'Student handout'), (2, 'Teacher reference'), (3, 'Slides'), (3, 'Code'), (5, 'Schematic')], default=0),
        ),
    ]
