# Generated by Django 2.0.6 on 2018-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_auto_20180703_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
