# Generated by Django 2.0.7 on 2018-09-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_auto_20180808_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='semantic_type',
            field=models.SmallIntegerField(choices=[(0, 'Other'), (1, 'Student handout'), (2, 'Teacher reference'), (3, 'Slides'), (4, 'Code'), (5, 'Schematic')], default=0),
        ),
    ]
