# Generated by Django 2.0.7 on 2018-09-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_auto_20180912_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfeedback',
            name='notify_author_of_changes',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='notify_of_feedback',
        ),
    ]
