# Generated by Django 2.1.7 on 2019-05-23 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0014_auto_20180912_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResourceExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('semantic_type', models.SmallIntegerField(choices=[(0, 'Other'), (1, 'Student handout'), (2, 'Teacher reference'), (3, 'Slides'), (4, 'Code'), (5, 'Schematic')], default=0)),
                ('link', models.URLField(max_length=400)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='resource_links',
            field=models.ManyToManyField(blank=True, to='curriculum.LessonResourceExternalLink'),
        ),
    ]
