# Generated by Django 2.2.10 on 2020-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_auto_20190523_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='materials',
            field=models.TextField(),
        ),
    ]
