# Generated by Django 2.2.10 on 2020-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_auto_20200419_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='summary',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
