# Generated by Django 2.2.10 on 2020-04-19 19:06

from django.db import migrations, models
import django.db.models.deletion

def split_materials(apps, schema_editor):
    LessonPlan = apps.get_model('curriculum', 'LessonPlan')
    Material = apps.get_model('curriculum', 'Material')

    for lesson_plan in LessonPlan.objects.all():
        materials = lesson_plan.materials.split('\n')
        for material_name in materials:
            trimmed_name = material_name.strip()
            if trimmed_name:
                new_material = Material(lesson_plan=lesson_plan, name=trimmed_name)
                new_material.save()

def join_materials(apps, schema_editor):
    LessonPlan = apps.get_model('curriculum', 'LessonPlan')
    Material = apps.get_model('curriculum', 'Material')

    for lesson_plan in LessonPlan.objects.all():
        materials = lesson_plan.material_set.all()
        materials_combined = '\n'.join([mat.name for mat in materials])
        lesson_plan.materials = materials_combined
        lesson_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20200419_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.LessonPlan')),
            ],
        ),
        migrations.RunPython(split_materials, reverse_code=join_materials),
        migrations.RemoveField(
            model_name='lessonplan',
            name='materials',
        ),
    ]
