# Generated by Django 3.0.5 on 2020-04-26 18:22

from django.db import migrations, models


def associate_materials(apps, schema_editor):
    LessonPlan = apps.get_model('curriculum', 'LessonPlan')

    for lesson_plan in LessonPlan.objects.all():
        for material in lesson_plan.material_set.all():
            lesson_plan.materials.add(material)
        lesson_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_auto_20200419_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='materials',
            field=models.ManyToManyField(blank=True, to='curriculum.Material'),
        ),
        migrations.RunPython(associate_materials),
        migrations.RemoveField(
            model_name='material',
            name='lesson_plan',
        ),
    ]
